### ISSUE TITLE
DC section - Remaining data credits/bytes numbers not aligned

### ISSUE THREAD

**Issue by jdgemm** [helium/roaming-console#31]
latest chrome, seems to be wrapping issue

<img width="1138" alt="Screen Shot 2022-03-03 at 11 38 41 AM" src="https://user-images.githubusercontent.com/36315460/156640081-4e37e387-fdea-47f5-ad5b-31ed82adf491.png">

does not happen on regular Console

<img width="870" alt="Screen Shot 2022-03-03 at 11 38 59 AM" src="https://user-images.githubusercontent.com/36315460/156640121-4e799741-1752-47f2-89db-7f5693f1e0d7.png">

**Comment by ambuznego** [comment]
> does not happen on regular Console
the number wasn't big enough on console to cause the same issue.
fixed nonetheless.
