### ISSUE TITLE
Alert: dc balance low, more details about when alert sent

### ISSUE THREAD

**Issue by jdgemm** [helium/roaming-console#33]
Add more details when alert sent:

Notify Admin when Data Credit balance is low (below 500,000 and at 0)

<img width="1073" alt="Screen Shot 2022-03-03 at 12 11 58 PM" src="https://user-images.githubusercontent.com/36315460/156645051-f8946eb9-321d-462a-8fd1-867d6f4e3822.png">

**Comment by ambuznego** [comment]
Addressed in commit [895dd07783d1bb46e018d02cb298756ee2b0ccb5](https://github.com/helium/roaming-console/commit/895dd07783d1bb46e018d02cb298756ee2b0ccb5)

<img width="922" alt="image" src="https://user-images.githubusercontent.com/51131939/156648294-546ccaed-1d27-4b20-8f0e-fb03f8532fe2.png">
