### ISSUE TITLE
Dashboard graph additional details

### ISSUE THREAD

**Issue by jdgemm** [helium/roaming-console#34]
update: 

Packets Transferred 

to

Packets Transferred (last 24 hrs, updated every 5 minutes)

**Comment by ambuznego** [comment]
Addressed by commit [ed8669f2716156ddcbb1537cea18b2021f1566b2](https://github.com/helium/roaming-console/commit/ed8669f2716156ddcbb1537cea18b2021f1566b2)

<img width="631" alt="image" src="https://user-images.githubusercontent.com/51131939/156663952-f18f31b1-65eb-41a8-bf5c-1246ff8746be.png">
