### ISSUE TITLE
dashboard provide additional time horizons for packets sent/dc used

### ISSUE THREAD

**Issue by jdgemm** [helium/roaming-console#35]
As a user I want to compare packets I'm seeing at my endpoint with the roaming Console metrics. 

Provide a 24 hr view of total packets sent and total dc used.

**Comment by vicmgs** [comment]
how are they tracking 24 hours? midnight to midnight? real time rolling 24 hours?

**Comment by jdgemm** [comment]
let's do a rolling 24 hrs, it's more about them just getting a gauge and comparing what they're seeing on their end vs exact mapping to their system which could be different from others...
