### ISSUE TITLE
Update UI text to help users

### ISSUE THREAD

**Issue by jdgemm** [helium/roaming-console#43]
Additional content on UI to make it easier for users

Multi-packet purchase

 Pay for additional packets (if available) for redundancy and location triangulation purposes. Enter the number of desired packets. Note: additional packets can only be purchased if multiple Hotspots "hear" and send the same packet. By default only 1 packet is purchased.

Join Credentials

Enter device DevEUI and AppEUI/JoinEUIs (only hex values accepted). Multiple DevEUI’s mapped to a single AppEUI can be added using an asterisk wildcard “*” in the DevEUI field with the specific AppEUI. Each new AppEUI requires a new entry.

Alerts

Email alerts can be set up for a number of conditions related to Data Credit balance, user management, or payment methods. User types (e.g., Administrator or Managers) can be specified to receive alert.

**Comment by ambuznego** [comment]
You'd like this under the labels on the config page or as tooltips?

**Comment by jdgemm** [comment]
under labels on config page...

**Comment by jdgemm** [comment]
updated:

Multi-packet purchase

Enter the number of desired packets (if available). Additional packets are purchased only if multiple Hotspots "hear" and send the same packet. 

Join Credentials

Use an asterisk “*” wildcard in the DevEUI field to map multiple DevEUI's to a single AppEUI. Each AppEUI requires a new entry.

Alerts

Email alerts can be set up for a number of conditions related to Data Credit balance, user management, or payment methods. User types (e.g., Administrator or Managers) can be specified to receive alert.
