### ISSUE TITLE
Tell packet purchaser to stop purchasing per net ID, not collectively

### ISSUE THREAD

**Issue by ambuznego** [helium/roaming-console#52]
Currently, when running out of DC, roaming console will broadcast `stop_purchasing` with `%{ net_ids: net_id_values }` to packet purchaser. Change it to broadcast once per net_id.

**Comment by ambuznego** [comment]
@michaeldjeffrey would you like the same change for `keep_purchasing`?

**Comment by michaeldjeffrey** [comment]
yes please.
